name: Strip widget metadata

on:
  push:
    paths:
      - '**.ipynb'

jobs:
  strip_widgets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install nbformat
        run: pip install nbformat

      - name: Strip metadata.widgets from notebooks
        run: |
          python - << 'EOF'
          import nbformat, glob
          changed = False
          for path in glob.glob('**/*.ipynb', recursive=True):
              nb = nbformat.read(path, as_version=4)
              for cell in nb.cells:
                  if 'widgets' in cell.metadata:
                      cell.metadata.pop('widgets')
                      changed = True
              if changed:
                  nbformat.write(nb, path)
                  print(f"Stripped widgets from {path}")
                  changed = False
          EOF

      - name: Commit & push cleaned notebooks
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || \
            (git commit -m "ci: strip metadata.widgets from notebooks" && git push)
